version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_expensetracker
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: expensetracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: